// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://heurpehcwbhohwklqnir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldXJwZWhjd2Job2h3a2xxbmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1Mjg1OTAsImV4cCI6MjA4OTEwNDU5MH0.53GF3SNG4gmwUGKNdaZx5i8PVy4f73FN7x53jna_l9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Persist the session to localStorage so refresh keeps users signed in.
    persistSession: true,
    // Automatically refresh the access token before it expires.
    autoRefreshToken: true,
    // Detect OAuth / magic-link callbacks in the URL on load.
    detectSessionInUrl: true,
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    // Explicit, project-scoped storage key so the persisted session survives reloads
    // and never collides with another Supabase project on the same origin.
    storageKey: "sb-heurpehcwbhohwklqnir-auth-token",
    flowType: "pkce",
  },
});
